Diff_Drive:
  diff_drive_controller:
     type: "diff_drive_controller/DiffDriveController"
     publish_rate: 50

     left_wheel: ['RL']
     right_wheel: ['RR']

     wheel_separation: 1.18
     wheel_radius: 0.254
     # Odometry covariances for the encoder output of the robot. These values should
     # be tuned to your robot's sample odometry data, but these values are a good place
     # to start
     pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
     twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
     # Top level frame (link) of the robot description
     base_frame_id: Body_base_link
 
     # Velocity and acceleration limits for the robot
     linear:
       y:
         has_velocity_limits    : true
         max_velocity           : 10  # m/s
         has_acceleration_limits: true
         max_acceleration       : 30   # m/s^2
     angular:
       z:
         has_velocity_limits    : true
         max_velocity           : 10   # rad/s
         has_acceleration_limits: true
         max_acceleration       : 30   # rad/s^2
